services:

  app1:
    build:
      context: .
      dockerfile: Dockerfile.app1
    container_name: app1

  app2:
    build:
      context: .
      dockerfile: Dockerfile.app2
    container_name: app2

  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
